# general settings
name: train_HMA_SRx2_from_imagenet_800k_cpu
model_type: HMAModel
scale: 2
num_gpu: 0  # Establecido a 0 para indicar uso de CPU
manual_seed: 1234

# dataset and data loader settings
datasets:
  train:
    name: ImageNet
    type: PairedImageNetDataset
    dataroot_gt: ./datasets/imagenet/imagenet
    meta_info_file: ./datasets/imagenet/imagenet.txt
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4  # Reducido para CPU
    batch_size_per_gpu: 2  # Reducido para CPU
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_1:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: ./datasets/set5/GTmod2
    dataroot_lq: ./datasets/LRbicx2
    io_backend:
      type: disk

# network structures
network_g:
  type: HMANet
  upscale: 2
  in_chans: 3
  img_size: 64
  window_size: 16
  interval_size: 4
  img_range: 1.0
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: 0.0002
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [300000, 500000, 650000, 700000, 750000]
    gamma: 0.5

  total_iter: 800000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: 1000.0
  save_img: false
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: 5000.0
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: none  # Cambiado a 'none' ya que no usaremos entrenamiento distribuido
  port: 29500
